# Generated by Django 3.2 on 2021-04-21 19:40

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNum', models.IntegerField()),
                ('file', models.FileField(upload_to='invoices', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceNum', models.IntegerField(primary_key=True, serialize=False)),
                ('invoiceDate', models.CharField(default='', max_length=20)),
                ('buyer', models.CharField(max_length=100)),
                ('buyerAddress', models.CharField(default='', max_length=1000)),
                ('seller', models.CharField(max_length=100)),
                ('sellerAddress', models.CharField(default='', max_length=1000)),
                ('lineItems', jsonfield.fields.JSONField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default='Uploaded', max_length=100)),
            ],
        ),
    ]
